### ISSUE TITLE
Crash when executing gears-linux 0.1.0 release

### ISSUE THREAD

**Issue by nvuaille** [Chapitalists/Gears#1]
On archlinux:

```
./gears-linux
[1]    49861 segmentation fault (core dumped)  ./gears-linux
```

More output on gdb:
```
Thread 1 "gears-linux" received signal SIGSEGV, Segmentation fault.
0x00000000011c5434 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::GetBackReferencedObject(int) ()
(gdb) bt
#0  0x00000000011c5434 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::GetBackReferencedObject(int) ()
#1  0x00000000011c93b7 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#2  0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#3  0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#4  0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#5  0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#6  0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#7  0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#8  0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#9  0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#10 0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#11 0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#12 0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#13 0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#14 0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#15 0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#16 0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#17 0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#18 0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#19 0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#20 0x00000000011c8dba in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#21 0x00000000011c9ec9 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#22 0x00000000011ca9a8 in v8::internal::ObjectDeserializer::Deserialize(v8::internal::Isolate*) ()
#23 0x00000000011cb4a1 in v8::internal::ObjectDeserializer::DeserializeSharedFunctionInfo(v8::internal::Isolate*, v8::internal::SerializedCodeData const*, v8::internal::Handle<v8::internal::String>) ()
#24 0x00000000011c0260 in v8::internal::CodeSerializer::Deserialize(v8::internal::Isolate*, v8::internal::ScriptData*, v8::internal::Handle<v8::internal::String>) ()
#25 0x0000000000bf4465 in v8::internal::Compiler::GetSharedFunctionInfoForScript(v8::internal::Handle<v8::internal::String>, v8::internal::Compiler::ScriptDetails const&, v8::ScriptOriginOptions, v8::Extension*, v8::internal::ScriptData*, v8::ScriptCompiler::CompileOptions, v8::ScriptCompiler::NoCacheReason, v8::internal::NativesFlag) ()
#26 0x0000000000ac6cd4 in v8::ScriptCompiler::CompileUnboundInternal(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions, v8::ScriptCompiler::NoCacheReason) ()
#27 0x0000000000902acc in node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) ()
#28 0x0000000000b393b5 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
#29 0x00003a9b4f95be1d in ?? ()
#30 0x00007fffffffbc10 in ?? ()
#31 0x00003a9b4f95bd81 in ?? ()
#32 0x00007fffffffc0e0 in ?? ()
#33 0x0000000000000006 in ?? ()
#34 0x00007fffffffc190 in ?? ()
#35 0x00003a9b4f90d145 in ?? ()
#36 0x00000c3fdd79cd61 in ?? ()
#37 0x000006e8998b68b1 in ?? ()
#38 0x0000000d00000000 in ?? ()
#39 0x00000d8823702801 in ?? ()
#40 0x00000d88237029a1 in ?? ()
#41 0x00000d88237026f1 in ?? ()
#42 0x00000d88237029a1 in ?? ()
#43 0x000004292076d4c9 in ?? ()
#44 0x0000000000000000 in ?? ()
```

**Comment by cbossut** [comment]
Tried a different way to package for new release, does it work?

**Comment by nvuaille** [comment]
Yup, nice !
