### ISSUE TITLE
Error when trying README commands

### ISSUE THREAD

**Issue by nvuaille** [Chapitalists/Gears#2]
First part seems OK
``` bash
$ elm make --output=elmApp.js src/Main.elm
Starting downloads...

  ● elm/file 1.0.5
  ● elm/html 1.0.0
  ● elm/virtual-dom 1.0.2
  ● elm/json 1.1.3
  ● elm/svg 1.0.1
  ● NoRedInk/elm-json-decode-pipeline 1.0.0
  ● zaboco/elm-draggable 4.0.5
  ● ljuglaret/fraction 1.0.0
  ● Chadtech/id 4.2.0
  ● elm-community/undo-redo 3.0.0
  ● elm-explorations/linear-algebra 1.0.3
  ● webbhuset/elm-json-decode 1.0.2
  ● elm/random 1.0.0
  ● elm/http 2.0.0
  ● elm/time 1.0.0
  ● elm/bytes 1.0.8
  ● avh4/elm-color 1.0.0
  ● krisajenkins/remotedata 6.0.1
  ● mpizenberg/elm-pointer-events 4.0.1
  ● elm/url 1.0.0
  ● elm-community/typed-svg 5.1.0
  ● elm/browser 1.0.2
  ● elm/core 1.0.2
  ● mdgriffith/elm-ui 1.1.5

Dependencies ready!           
Success! Compiled 10 modules.

    Main ───> elmApp.js
``` 

Second part fails:
``` bash
$ node index.js 
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module 'static-route'
Require stack:
- /home/nicolas/Documents/perso/Gears/Gears/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/nicolas/Documents/perso/Gears/Gears/index.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/nicolas/Documents/perso/Gears/Gears/index.js' ]
}
```

**Comment by cbossut** [comment]
Added package.json to install dependencies with npm install.
Is it fixed ?
